version: '3.4'

services: 

  frontend:
    image: storeimage
    build:
      context: .
      dockerfile: DockerfileStore
    environment: 
      - ProductEndpoint=http://backend:8080
      - ImagePrefix=http://localhost:33001/images
    ports:
      - "33000:8080"
    depends_on: 
      - backend
  backend:
    image: productservice
    build: 
      context: .
      dockerfile: DockerfileProducts
    ports: 
      - "33001:8080"